<a href="https://colab.research.google.com/github/jmishra01/AI-ML/blob/main/ML_01_LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [3]:
# Data url & file name
data = "https://raw.githubusercontent.com/jmishra01/AI-ML/refs/heads/main/data/Real-estate.csv"
file_name = "Real-estate.csv"

In [4]:
# Dowload csv file using requests library
import requests

res = requests.get(data)
if res.status_code == 200:
    with open(file_name, 'wb') as f:
        f.write(res.content)

In [5]:
# Display first 5 rows
!head -n 5 Real-estate.csv

No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
1,2012.917,32,84.87882,10,24.98298,121.54024,37.9
2,2012.917,19.5,306.5947,9,24.98034,121.53951,42.2
3,2013.583,13.3,561.9845,5,24.98746,121.54391,47.3
4,2013.500,13.3,561.9845,5,24.98746,121.54391,54.8

In [6]:
# Read csv file, and create pandas dataframe
df = pd.read_csv(file_name)

In [7]:
columns = ["No", "trans-date", "house-age", "dist-mrt-stn", "#-stores", "lat", "lng", "price-per-unit"]
df.columns = columns
df = df[columns[1:]]

In [8]:
df.head()

,trans-date,house-age,dist-mrt-stn,#-stores,lat,lng,price-per-unit
0,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1

In [9]:
X = df.drop("price-per-unit", axis=1)
y = df["price-per-unit"]

In [10]:
X.head()

   trans-date  house-age  dist-mrt-stn  #-stores       lat        lng
0    2012.917       32.0      84.87882        10  24.98298  121.54024
1    2012.917       19.5     306.59470         9  24.98034  121.53951
2    2013.583       13.3     561.98450         5  24.98746  121.54391
3    2013.500       13.3     561.98450         5  24.98746  121.54391
4    2012.833        5.0     390.56840         5  24.97937  121.54245

In [11]:
y.head()

0    37.9
1    42.2
2    47.3
3    54.8
4    43.1
Name: price-per-unit, dtype: float64

In [12]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split, StratifiedKFold, GridSearchCV
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer

from sklearn.linear_model import LinearRegression as LR

In [13]:
RANDOM_STATE = 42

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=RANDOM_STATE)

In [15]:
numeric_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer([
    ('numeric', numeric_pipe, X.select_dtypes(include=['int64', 'float64']).columns),
    ('categorical', categorical_pipe, X.select_dtypes(include=['object']).columns)
])

full_pipe = Pipeline([
    ('preprocessor', preprocessor),
    ('model', LR())
])

In [16]:
full_pipe.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('numeric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['trans-date', 'house-age', 'dist-mrt-stn', '#-stores', 'lat', 'lng'], dtype='object')),
                                                 ('categorical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index([], dtype='object'))])),
                ('model', LinearRegression())])

In [17]:
# Predict y_pred values using predict function.
y_pred = full_pipe.predict(X_test)

In [22]:
from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score
    )

In [19]:
mean_squared_error(y_test, y_pred)

53.505619124502054

In [20]:
mean_absolute_error(y_test, y_pred)

5.305355690074041

In [21]:
r2_score(y_test, y_pred)

0.6810580555095946